### ISSUE TITLE
After executing command “docker build -t look-for-the-change .”, an error is reported

### ISSUE THREAD

**Issue by wang136618693** [soCzech/LookForTheChange#1]
Hello, when I execute the command "docker build -t look for the change." An error is reported when.The error is as follows：

E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec57_3.4.11-0ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/libasound2-data_1.1.3-5ubuntu0.6_all.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/libb/libbs2b/libbs2b0_3.1.0+dfsg-2.2_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/flite/libflite1_2.1-release-1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/fftw3/libfftw3-double3_3.3.7-1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/n/norm/libnorm1_1.5r6+dfsg1-6_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libc/libcdio/libcdio17_1.0.0-2ubuntu2_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libc/libcdio-paranoia/libcdio-cdda2_10.2+0.94+2-2build1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavdevice57_3.4.11-0ubuntu0.1_amd64.deb  Connection failed [IP: 185.125.190.36 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/ffmpeg_3.4.11-0ubuntu0.1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Hope to answer as soon as possible, thank you!

**Comment by soCzech** [comment]
This error is not related to the project. Check your internet connection and possibly try to resolve the issue in ubuntu or docker forums.
