### ISSUE TITLE
Could you please provide the environment list?

### ISSUE THREAD

**Issue by jshi31** [soCzech/LookForTheChange#2]
Hi, seems all the environment is in docker. Could you please use provide the environment list in case we cannot use docker? Thanks

**Comment by soCzech** [comment]
Here it is:
https://github.com/soCzech/LookForTheChange/blob/main/Dockerfile#L7-L17
Plus `pytorch` obviously.

But keep in mind, you need a correct instalation of cudatoolkit (i.e. compatible with the versions of the installed python packages) with all paths correctly defined.

Plus you need `ffmpeg` and probably other tools instaled with their locations in `PATH` to be able to run the scripts.
