### ISSUE TITLE
Feature extraction augment times

### ISSUE THREAD

**Issue by jshi31** [soCzech/LookForTheChange#4]
I notice that extract the feature requires 10 augmentation, which means each video it will store 11 augmented feature, and the feature extraction process is too long. Does the augmentation matter much? I want to just run 0 augmentation to accelerate the feature extraction speed, is this a bad idea?

**Comment by soCzech** [comment]
See https://arxiv.org/abs/2203.11637.
TL;DR: Yes, it is possible to set it to zero.
